### ISSUE TITLE
Can't compile dependency

### ISSUE THREAD

**Issue by fuelen** [Qqwy/elixir-type_check#28]
```
mix deps.compile type_check                                                                                                                                                                                                 1 ↵ fuelen@arch
==> type_check
Compiling 39 files (.ex)

== Compilation error in file lib/type_check/type.ex ==
** (CompileError) lib/type_check/type.ex:18: cannot import TypeCheck.Builtin.|/2 because it conflicts with Elixir special forms
    (elixir 1.11.0-rc.0) src/elixir_import.erl:96: :elixir_import.calculate/6
    (elixir 1.11.0-rc.0) src/elixir_import.erl:24: :elixir_import.import/4
```
```
elixir 1.11.0-rc.0-otp-22
erlang 22.3.4.10
```

**Comment by Qqwy** [comment]
Thank you. I think this is a change introduced in a recent Elixir version.
Obviously it falls to TypeCheck to make sure it still works correctly. (Using `|` as a function directly can be considered depending on internal implementation details of Elixir's runtime, and when those are altered it is not considered a breaking change.)

**Comment by Qqwy** [comment]
I hereby confirm that it works correctly in Elixir `1.10.3` (with Erlang `23.0`) and breaks for Elixir `1.11.0-rc.0-otp-23`.
