### ISSUE TITLE
Package doesn't compile on Elixir 1.19

### ISSUE THREAD

**Issue by Noarkhh** [Qqwy/elixir-type_check#210]
Hello, unfortunately the package no longer compiles as of Elixir 1.19:

```
==> type_check
Compiling 123 files (.ex)

== Compilation error in file lib/type_check/default_overrides/regex.ex ==
** (Kernel.TypespecError) lib/type_check/default_overrides/regex.ex:5: undefined field :re_ver
sion on struct Regex
    (elixir 1.19.4) lib/kernel/typespec.ex:992: Kernel.Typespec.compile_error/2
    (stdlib 7.1) lists.erl:2641: :lists.foreach_1/2
    (elixir 1.19.4) lib/kernel/typespec.ex:617: Kernel.Typespec.typespec/4
    (elixir 1.19.4) lib/kernel/typespec.ex:312: Kernel.Typespec.translate_type/2
    (stdlib 7.1) lists.erl:2673: :lists.mapfoldl_1/3
    (elixir 1.19.4) lib/kernel/typespec.ex:239: Kernel.Typespec.translate_typespecs_for_module
/2
could not compile dependency :type_check, "mix compile" failed. Errors may have been logged ab
ove. You can recompile this dependency with "mix deps.compile type_check --force", update it w
ith "mix deps.update type_check" or clean it with "mix deps.clean type_check"
```

The error stems from the fact that in Elixir 1.19 `Regex.t()` struct lost the `:re_version` field, which is used in `type_check/default_overrides/regex.ex`. Elixir documentation discloses that "Keep in mind that all of the structs fields are private.", which makes me unsure what would be the best solution, hence I open an issue rather than a PR.
