### PR TITLE
Elixir v1.15.0 support

### LINKED ISSUE #185: Error in Elixir 1.15 trying to use the module TypeCheck.Type which is currently being defined
After upgrading to Elixir `1.15.0 (compiled with Erlang/OTP 25)` we're faced with this error at compile time:

``` elixir
error: you are trying to use/import/require the module TypeCheck.Type which is currently being defined.

This may happen if you accidentally override the module you want to use. For example:

    defmodule MyApp do
      defmodule Supervisor do
        use Supervisor
      end
    end

In the example above, the new Supervisor conflicts with Elixir's Supervisor. This may be fixed by using the fully qualified name in the definition:

    defmodule MyApp.Supervisor do
      use Supervisor
    end

  lib/type_check.ex:141: TypeCheck.Type (module)


== Compilation error in file lib/type_check/internals/bootstrap.ex ==
** (CompileError) lib/type_check/type.ex: cannot compile module TypeCheck.Type (errors have been logged)
    expanding macro: TypeCheck.__using__/1
    lib/type_check/type.ex:7: TypeCheck.Type (module)
    (elixir 1.15.0) expanding macro: Kernel.use/1
    lib/type_check/type.ex:7: TypeCheck.Type (module)
    expanding macro: TypeCheck.Internals.Bootstrap.Macros.if_recompiling?/1
```

The error does NOT occur in previous version Elixir `1.14.5 (compiled with Erlang/OTP 25)`

### PR DESCRIPTION
**Pull request by Qqwy**
This PR ensures TypeCheck can be used with Elixir v1.15.0

A huge thanks to @josevalim for not only giving guidance on what changes might be required to make TypeCheck compile on Elixir v1.15.0, but even contributing with a complete set of changes to make this work.

This PR continues on [that patch](https://github.com/elixir-lang/elixir/issues/12726#issuecomment-1614762113), doing some more changes to make sure the test suite also compiles and fixing some edge cases.

### Turning all `@spec!` to non-checked `@spec` in the `TypeCheck.Builtin` module. 

**This is hopefully a temporary change, as it means the library is doing less dogfooding and less compile-time checks of its own usage.**

It was necessary since on v1.15, with the patch in place that prevents "importing TypeCheck.Builtin into itself" which is no longer supported, another approach to add the specs and the spectests need to be found. 

_In the worst case, these could be turned into in-function-body calls to `TypeCheck.conforms!` that do not rely on the macro magic of `@spec!`._

### Fixing some tests relying on particular output of `CompileError`. 

The structure of compile-time error message reporting was changed somewhat in v1.15, so some tests now are conditionally compiled to match the new format and messages. 

### Fixing some doctests

There was a weird situation in which using the `@spec!` syntax in a doctest ate the next line that started with `...(2)>` as well. Changing this to `iex(2)>` resolved it.

Fixes #185 

- [x] Fix compilation
- [x] Fix tests
- [x] Update Changelog
- [ ] Release new version

### CODE REVIEW

**Comment by Qqwy** [comment]
I also had to make a small change to the CI system: `mix format` formats some files slightly differently on v1.15, so the check has moved to a separate CI job which only runs on v1.15.
